
modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/LCLPYT/LCLPMMO/issues"
displayURL="https://github.com/LCLPYT/LCLPMMO"
authors="LCLP"

[[mods]]
    modId="lclpmmo"
    version="${version}"
    displayName="LCLPMMO"
    updateJSONURL="https://raw.githubusercontent.com/LCLPYT/LCLPMMO/master/LCLPMMO/update.json"
    logoFile="logo.png"
    credits="LCLPNetwork!"
    description='''
    A modification that adds MMO stuff to Minecraft.
    Intended to be used on LCLPServer 5.0.
    '''

    [[dependencies.core]]
        modId="corebase"
        mandatory=true
        versionRange="[1.3,)"
        ordering="BEFORE"
        side="BOTH"
    [[dependencies.core]]
        modId="forge"
        mandatory=true
        versionRange="[31,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.core]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.15.2]"
        ordering="NONE"
        side="BOTH"

