modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/LCLPYT/LCLPMMO/issues"
displayURL="https://github.com/LCLPYT/LCLPMMO"
authors="LCLP"
license="MIT"

[[mods]]
    modId="lclpmmo"
    version="${version}"
    displayName="LCLPMMO"
    updateJSONURL="https://raw.githubusercontent.com/LCLPYT/LCLPMMO/master/update.json"
    logoFile="logo.png"
    credits="LCLPNetwork!"
    description='''
    A modification that adds MMO stuff to Minecraft.
    Intended to be used on LCLPServer 5.0.
    '''

    [[dependencies.core]]
        modId="corebase"
        mandatory=true
        versionRange="[1.5,)"
        ordering="BEFORE"
        side="BOTH"
    [[dependencies.core]]
        modId="forge"
        mandatory=true
        versionRange="[34,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.core]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.3]"
        ordering="NONE"
        side="BOTH"

