modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/LCLPYT/LCLPMMO/issues"
displayURL="https://github.com/LCLPYT/LCLPMMO"
authors="LCLP"
license="MIT"

[[mods]]
    modId="lclpmmo"
    version="${version}"
    displayName="LCLPMMO"
    updateJSONURL="https://raw.githubusercontent.com/LCLPYT/LCLPMMO/master/update.json"
    logoFile="logo.png"
    credits="LCLPNetwork!"
    description='''
    A modification that adds MMO stuff to Minecraft.
    Intended to be used on LCLPServer 5.0.
    '''

    [[dependencies.lclpmmo]]
        modId="corebase"
        mandatory=true
        versionRange="[1.6,)"
        ordering="BEFORE"
        side="BOTH"
    [[dependencies.lclpmmo]]
        modId="forge"
        mandatory=true
        versionRange="[36,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.lclpmmo]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.5]"
        ordering="NONE"
        side="BOTH"

